<?php
/*
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
define("SC2_TYPEUNIT", 1); // normal units
define("SC2_TYPEWORKER", 2); // workers, Drone/SCV/Probe, MULE calldown
define("SC2_TYPEBUILDING", 3); // any kind of buildings
define("SC2_TYPEADDON", 4); // building addons(terran)
define("SC2_TYPEUPGRADE", 5); // any kind of upgrade
define("SC2_TYPEABILITY", 6); // a unit or building ability that is not an upgrade
define("SC2_TYPEBUILDINGUPGRADE",7); // transform a building to another building
define("SC2_TYPEGEN", 8); // anything that doesn't fit into earlier categories

define("SC2_SUBTYPECREATE", 1); // opposite of cancel
define("SC2_SUBTYPECANCEL", 2); // cancel
class SC2ReplayUtils {
	public static $ABILITYCODES = array(
		// terran
		0x030D00 => array('desc' => 'builds Point defense drone (Raven)', 'name' => 'Point defense drone (Raven)', 'type' => SC2_TYPEABILITY),
		0x040900 => array('desc' => 'uses Seeker missile (Raven)', 'name' => 'Seeker missile (Raven)', 'type' => SC2_TYPEABILITY),
		0x040A00 => array('desc' => 'calls down a MULE', 'name' => 'MULE', 'type' => SC2_TYPEWORKER, 'subtype' => SC2_SUBTYPECREATE, 'min' => 0, 'gas' => 0, 'sup' => 0),
		0x050600 => array('desc' => 'sets rally point (Generic)', 'name' => 'rally point (Generic)', 'type' => SC2_TYPEGEN),
		0x060000 => array('desc' => 'uses Stim pack (Marauder)', 'name' => 'Stim pack', 'type' => SC2_TYPEABILITY),
		0x060100 => array('desc' => 'calls down supplies (Orbital command)', 'name' => 'Calldown: Extra supplies (Orbital command)', 'type' => SC2_TYPEABILITY),
		0x060200 => array('desc' => 'uses 250mm strike cannons (Thor)', 'name' => '250mm strike cannons (Thor)', 'type' => SC2_TYPEABILITY),
		0x060701 => array('desc' => 'returns cargo (SCV)', 'name' => 'return cargo (SCV)', 'type' => SC2_TYPEGEN),
		0x060B00 => array('desc' => 'cancels a build in progress (Starport)', 'name' => 'cancel (Starport)', 'type' => SC2_TYPEGEN, 'subtype' => SC2_SUBTYPECANCEL), // medivac
		0x060B01 => array('desc' => 'cancels a build in progress', 'name' => 'cancel', 'type' => SC2_TYPEGEN, 'subtype' => SC2_SUBTYPECANCEL),
		0x060F00 => array('desc' => 'repairs', 'name' => 'repair', 'type' => SC2_TYPEGEN, 'subtype' => SC2_SUBTYPECANCEL),
		0x070000 => array('desc' => 'builds a Command center', 'name' => 'Command center', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 400, 'gas' => 0),
		0x070001 => array('desc' => 'builds a Supply depot', 'name' => 'Supply depot', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 0),
		0x070002 => array('desc' => 'builds a Refinery', 'name' => 'Refinery', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 75, 'gas' => 0),
		0x070003 => array('desc' => 'builds a Barracks', 'name' => 'Barracks', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 0),
		0x070004 => array('desc' => 'builds an Engineering Bay', 'name' => 'Engineering Bay', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 125, 'gas' => 0),
		0x070005 => array('desc' => 'builds a Missile turret', 'name' => 'Missile turret', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 0),
		0x070006 => array('desc' => 'builds a Bunker', 'name' => 'Bunker', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 0),
		0x070008 => array('desc' => 'builds a Sensor tower', 'name' => 'Sensor tower', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 125, 'gas' => 100),
		0x070009 => array('desc' => 'builds a Ghost academy', 'name' => 'Ghost academy', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 50),
		0x07000A => array('desc' => 'builds a Factory', 'name' => 'Factory', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 100),
		0x07000B => array('desc' => 'builds a Starport', 'name' => 'Starport', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 100),
		0x07000D => array('desc' => 'builds an Armory', 'name' => 'Armory', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 100),
		0x07000F => array('desc' => 'builds a Fusion core', 'name' => 'Fusion core', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x070200 => array('desc' => 'uses Stim pack (mixed units)', 'name' => 'Stim pack', 'type' => SC2_TYPEABILITY),
		0x070300 => array('desc' => 'uses Cloak (Ghost)', 'name' => 'Cloak (Ghost)', 'type' => SC2_TYPEABILITY),
		0x070301 => array('desc' => 'uses Decloak (Ghost)', 'name' => 'Decloak (Ghost)', 'type' => SC2_TYPEABILITY),
		0x070400 => array('desc' => 'uses Sniper round (Ghost)', 'name' => 'Sniper round (Ghost)', 'type' => SC2_TYPEABILITY),
		0x070600 => array('desc' => 'uses Siege mode (Siege tank)', 'name' => 'Siege mode (Siege tank)', 'type' => SC2_TYPEABILITY),
		0x070700 => array('desc' => 'uses Tank mode (Siege tank)', 'name' => 'Tank mode (Siege tank)', 'type' => SC2_TYPEABILITY),
		0x070800 => array('desc' => 'uses Cloak (Banshee)', 'name' => 'Cloak (Banshee)', 'type' => SC2_TYPEABILITY),
		0x070801 => array('desc' => 'uses Decloak (Banshee)', 'name' => 'Decloak (Banshee)', 'type' => SC2_TYPEABILITY),
		0x070903 => array('desc' => 'unloads unit (Medivac)', 'name' => 'unload (Medivac)', 'type' => SC2_TYPEABILITY),
		0x070A00 => array('desc' => 'uses Scanner sweep (Orbital command)', 'name' => 'Scanner sweep (Orbital command)', 'type' => SC2_TYPEABILITY),
		0x070B00 => array('desc' => 'uses Yamato cannon (Battlecruiser)', 'name' => 'Yamato cannon (Battlecruiser)', 'type' => SC2_TYPEABILITY),
		0x070C00 => array('desc' => 'uses Assault mode (Viking)', 'name' => 'Assault mode (Viking)', 'type' => SC2_TYPEABILITY),
		0x070D00 => array('desc' => 'uses Fighter mode (Viking)', 'name' => 'Fighter mode (Viking)', 'type' => SC2_TYPEABILITY),
		0x070E03 => array('desc' => 'unloads unit (Bunker)', 'name' => 'unload (Bunker)', 'type' => SC2_TYPEABILITY),
		0x080000 => array('desc' => 'lifts off (Command center)', 'name' => 'liftoff (Command center)', 'type' => SC2_TYPEABILITY),
		0x080100 => array('desc' => 'lands (Command center)', 'name' => 'land (Command center)', 'type' => SC2_TYPEABILITY),
		0x080200 => array('desc' => 'builds a Tech lab(Barracks)', 'name' => 'Tech lab(Barracks)', 'type' => SC2_TYPEADDON, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 25),
		0x080201 => array('desc' => 'builds a Reactor(Barracks)', 'name' => 'Reactor(Barracks)', 'type' => SC2_TYPEADDON, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 50),
		0x080300 => array('desc' => 'lifts off (Barracks)', 'name' => 'liftoff (Barracks)', 'type' => SC2_TYPEABILITY),
		0x080400 => array('desc' => 'builds a Tech lab(Factory)', 'name' => 'Tech lab(Factory)', 'type' => SC2_TYPEADDON, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 25),
		0x080401 => array('desc' => 'builds a Reactor(Factory)', 'name' => 'Reactor(Factory)', 'type' => SC2_TYPEADDON, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 50),
		0x080500 => array('desc' => 'lifts off (Factory)', 'name' => 'liftoff (Factory)', 'type' => SC2_TYPEABILITY),
		0x080600 => array('desc' => 'builds a Tech lab(Starport)', 'name' => 'Tech lab(Starport)', 'type' => SC2_TYPEADDON, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 25),
		0x080601 => array('desc' => 'builds a Reactor(Starport)', 'name' => 'Reactor(Starport)', 'type' => SC2_TYPEADDON, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 50),
		0x080700 => array('desc' => 'lifts off (Starport)', 'name' => 'liftoff (Starport)', 'type' => SC2_TYPEABILITY),
		0x080800 => array('desc' => 'lands (Factory)', 'name' => 'land (Factory)', 'type' => SC2_TYPEABILITY),
		0x080900 => array('desc' => 'lands (Starport)', 'name' => 'land (Starport)', 'type' => SC2_TYPEABILITY),
		0x080A00 => array('desc' => 'trains an SCV', 'name' => 'SCV', 'type' => SC2_TYPEWORKER, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 0, 'sup' => 1),
		0x080B00 => array('desc' => 'lands (Barracks)', 'name' => 'land (Barracks)', 'type' => SC2_TYPEABILITY),
		0x080C00 => array('desc' => 'lowers a Supply depot', 'name' => 'lower a Supply depot', 'type' => SC2_TYPEABILITY),
		0x080D00 => array('desc' => 'raises a Supply depot', 'name' => 'raises a Supply depot', 'type' => SC2_TYPEABILITY),
		0x080E00 => array('desc' => 'trains a Marine', 'name' => 'Marine', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 0, 'sup' => 1),
		0x080E01 => array('desc' => 'trains a Reaper', 'name' => 'Reaper', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 25, 'sup' => 1),
		0x080E02 => array('desc' => 'trains a Ghost', 'name' => 'Ghost', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150, 'sup' => 2),
		0x080E03 => array('desc' => 'trains a Marauder', 'name' => 'Marauder', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 75, 'gas' => 25, 'sup' => 2),
		0x080F01 => array('desc' => 'builds a Siege tank', 'name' => 'Siege tank', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 125, 'sup' => 3),
		0x080F04 => array('desc' => 'builds a Thor', 'name' => 'Thor', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 200, 'sup' => 6),
		0x080F05 => array('desc' => 'builds a Hellion', 'name' => 'Hellion', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 0, 'sup' => 2),
		0x090000 => array('desc' => 'builds a Medivac', 'name' => 'Medivac', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100, 'sup' => 2),
		0x090001 => array('desc' => 'builds a Banshee', 'name' => 'Raven', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 100, 'sup' => 3),
		0x090002 => array('desc' => 'builds a Raven', 'name' => 'Raven', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 200, 'sup' => 2),
		0x090003 => array('desc' => 'builds a Battlecruiser', 'name' => 'Battlecruiser', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 400, 'gas' => 300, 'sup' => 6),
		0x090004 => array('desc' => 'builds a Viking', 'name' => 'Viking', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 75, 'sup' => 2),
		0x090100 => array('desc' => 'researches Hi-sec auto tracking', 'name' => 'Hi-sec auto tracking', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090101 => array('desc' => 'researches Structure armor', 'name' => 'Structure armor', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x090102 => array('desc' => 'researches Infantry weapons level 1', 'name' => 'Infantry weapons L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090103 => array('desc' => 'researches Infantry weapons level 2', 'name' => 'Infantry weapons L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x090104 => array('desc' => 'researches Infantry weapons level 3', 'name' => 'Infantry weapons L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x090105 => array('desc' => 'researches Neosteel frame', 'name' => 'Neosteel frame', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090106 => array('desc' => 'researches Infantry armor level 1', 'name' => 'Infantry armor L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090107 => array('desc' => 'researches Infantry armor level 2', 'name' => 'Infantry armor L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x090108 => array('desc' => 'researches Infantry armor level 3', 'name' => 'Infantry armor L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x090203 => array('desc' => 'researches Nitro packs', 'name' => 'Nitro packs', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 50),
		0x090300 => array('desc' => 'builds a Nuke', 'name' => 'Tactical nuke', 'type' => SC2_TYPEBUILDINGUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090400 => array('desc' => 'researches Stim pack', 'name' => 'Stim pack', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090401 => array('desc' => 'researches Combat shield', 'name' => 'Combat shield', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090402 => array('desc' => 'researches Concussive Shells', 'name' => 'Concussive shells', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 50),
		0x090500 => array('desc' => 'researches Siege tech', 'name' => 'Siege tech', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090501 => array('desc' => 'researches Infernal pre-igniter', 'name' => 'Infernal pre-igniter', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x090502 => array('desc' => 'researches 250mm strike cannons', 'name' => '250mm strike cannons', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x090600 => array('desc' => 'researches Cloaking field', 'name' => 'Cloaking field', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 200),
		0x090602 => array('desc' => 'researches Caduceus reactor', 'name' => 'Caduceus reactor', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090603 => array('desc' => 'researches Corvid reactor', 'name' => 'Corvid reactor', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x090606 => array('desc' => 'researches Seeker missile', 'name' => 'Seeker missile', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x090607 => array('desc' => 'researches Durable materials', 'name' => 'Durable materials', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x090700 => array('desc' => 'researches Personal cloaking', 'name' => 'Personal cloaking', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x090701 => array('desc' => 'researches Moebius reactor', 'name' => 'Moebius reactor', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090802 => array('desc' => 'researches Vehicle plating level 1', 'name' => 'Vehicle plating L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090803 => array('desc' => 'researches Vehicle plating level 2', 'name' => 'Vehicle plating L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x090804 => array('desc' => 'researches Vehicle plating level 3', 'name' => 'Vehicle plating L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x090805 => array('desc' => 'researches Vehicle weapons level 1', 'name' => 'Vehicle weapons L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x090806 => array('desc' => 'researches Vehicle weapons level 2', 'name' => 'Vehicle weapons L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x090807 => array('desc' => 'researches Vehicle weapons level 3', 'name' => 'Vehicle weapons L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x090808 => array('desc' => 'researches Ship plating level 1', 'name' => 'Ship plating L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x090809 => array('desc' => 'researches Ship plating level 2', 'name' => 'Ship plating L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 225, 'gas' => 225),
		0x09080A => array('desc' => 'researches Ship plating level 3', 'name' => 'Ship plating L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 300),
		0x09080B => array('desc' => 'researches Ship weapons level 1', 'name' => 'Ship weapons L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x09080C => array('desc' => 'researches Ship weapons level 2', 'name' => 'Ship weapons L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x09080D => array('desc' => 'researches Ship weapons level 3', 'name' => 'Ship weapons L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x0C0D00 => array('desc' => 'upgrades to Planetary fortress', 'name' => 'Planetary fortress', 'type' => SC2_TYPEBUILDINGUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0D0300 => array('desc' => 'upgrades to Orbital command', 'name' => 'Orbital command', 'type' => SC2_TYPEBUILDINGUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 0),
		0x0D0600 => array('desc' => 'lifts off (Orbital command)', 'name' => 'liftoff (Orbital command)', 'type' => SC2_TYPEABILITY),
		0x0D0700 => array('desc' => 'lands (Orbital command)', 'name' => 'land (Orbital command)', 'type' => SC2_TYPEABILITY),
		0x0D0B00 => array('desc' => 'researches Weapon refit', 'name' => 'Weapon refit', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0D0B01 => array('desc' => 'researches Behemoth reactor', 'name' => 'Behemoth reactor', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0D0E00 => array('desc' => 'uses Tactical nuclear strike (Ghost)', 'name' => 'Tactical nuclear strike (Ghost)', 'type' => SC2_TYPEABILITY),
		0x0E0000 => array('desc' => 'salvages a Bunker', 'name' => 'salvage (Bunker)', 'type' => SC2_TYPEABILITY),
		0x0E0100 => array('desc' => 'uses EMP round (Ghost)', 'name' => 'EMP round (Ghost)', 'type' => SC2_TYPEABILITY),
		0x0F0A00 => array('desc' => 'builds auto-turret (Raven)', 'name' => 'Auto-turret (Raven)', 'type' => SC2_TYPEABILITY),

		// protoss


		0x030500 => array('desc' => 'researches Flux vanes', 'name' => 'Flux vanes', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x030501 => array('desc' => 'researches Graviton catapult', 'name' => 'Graviton catapult', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x030700 => array('desc' => 'uses Guardian shield (Sentry)', 'name' => 'Guardian shield (Sentry)', 'type' => SC2_TYPEABILITY),
		0x030A00 => array('desc' => 'builds a Mothership', 'name' => 'Mothership', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 400, 'gas' => 400, 'sup' => 8),
		0x030B00 => array('desc' => 'uses Feedback (High templar)', 'name' => 'Feedback (High templar)', 'type' => SC2_TYPEABILITY),
		0x030C00 => array('desc' => 'uses Mass recall (Mothership)', 'name' => 'Mass recall (Mothership)', 'type' => SC2_TYPEABILITY),
		0x030E00 => array('desc' => 'uses Hallucination - Archon (Sentry)', 'name' => 'Hallucination - Archon (Sentry)', 'type' => SC2_TYPEABILITY),
		0x030F00 => array('desc' => 'uses Hallucination - Colossus (Sentry)', 'name' => 'Hallucination - Colossus (Sentry)', 'type' => SC2_TYPEABILITY),
		0x040000 => array('desc' => 'uses Hallucination - High templar (Sentry)', 'name' => 'Hallucination - High templar (Sentry)', 'type' => SC2_TYPEABILITY),
		0x040100 => array('desc' => 'uses Hallucination - Immortal (Sentry)', 'name' => 'Hallucination - Immortal (Sentry)', 'type' => SC2_TYPEABILITY),
		0x040200 => array('desc' => 'uses Hallucination - Phoenix (Sentry)', 'name' => 'Hallucination - Phoenix (Sentry)', 'type' => SC2_TYPEABILITY),
		0x040300 => array('desc' => 'uses Hallucination - Probe (Sentry)', 'name' => 'Hallucination - Probe (Sentry)', 'type' => SC2_TYPEABILITY),
		0x040400 => array('desc' => 'uses Hallucination - Stalker (Sentry)', 'name' => 'Hallucination - Stalker (Sentry)', 'type' => SC2_TYPEABILITY),
		0x040500 => array('desc' => 'uses Hallucination - Void ray (Sentry)', 'name' => 'Hallucination - Void ray (Sentry)', 'type' => SC2_TYPEABILITY),
		0x040600 => array('desc' => 'uses Hallucination - Warp prism (Sentry)', 'name' => 'Hallucination - Warp prism (Sentry)', 'type' => SC2_TYPEABILITY),
		0x040700 => array('desc' => 'uses Hallucination - Zealot (Sentry)', 'name' => 'Hallucination - Zealot (Sentry)', 'type' => SC2_TYPEABILITY),
		0x040B00 => array('desc' => 'uses Graviton beam (Phoenix)', 'name' => 'Graviton beam (Phoenix)', 'type' => SC2_TYPEABILITY),
		0x050900 => array('desc' => 'sets rally point (Nexus)', 'name' => 'rally point (Nexus)', 'type' => SC2_TYPEGEN),
		0x060801 => array('desc' => 'returns cargo (Probe)', 'name' => 'return cargo (Probe)', 'type' => SC2_TYPEGEN),
		0x060E00 => array('desc' => 'cancels a build in progress', 'name' => 'cancel', 'type' => SC2_TYPEGEN, 'subtype' => SC2_SUBTYPECANCEL), // pylon
		0x060400 => array('desc' => 'uses Chrono boost (Nexus)', 'name' => 'Chrono boost (Nexus)', 'type' => SC2_TYPEABILITY),
		0x090900 => array('desc' => 'builds a Nexus', 'name' => 'Nexus', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 400, 'gas' => 0),
		0x090901 => array('desc' => 'builds a Pylon', 'name' => 'Pylon', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 0),
		0x090902 => array('desc' => 'builds an Assimilator', 'name' => 'Assimilator', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 75, 'gas' => 0),
		0x090903 => array('desc' => 'builds a Gateway', 'name' => 'Gateway', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 0),
		0x090904 => array('desc' => 'builds a Forge', 'name' => 'Forge', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 0),
		0x090905 => array('desc' => 'builds a Fleet beacon', 'name' => 'Fleet beacon', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 200),
		0x090906 => array('desc' => 'builds a Twilight council', 'name' => 'Twilight council', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 100),
		0x090907 => array('desc' => 'builds a Photon cannon', 'name' => 'Photon cannon', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 0),
		0x090909 => array('desc' => 'builds a Stargate', 'name' => 'Stargate', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x09090A => array('desc' => 'builds Templar archives', 'name' => 'Templar archives', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 200),
		0x09090B => array('desc' => 'builds Dark shrine', 'name' => 'Dark shrine', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 250),
		0x09090C => array('desc' => 'builds a Robotics bay', 'name' => 'Robotics bay', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 200),
		0x09090D => array('desc' => 'builds a Robotics facility', 'name' => 'Robotics facility', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 100),
		0x09090E => array('desc' => 'builds a Cybernetics core', 'name' => 'Cybernetics core', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 0),
		0x090B00 => array('desc' => 'trains a Zealot', 'name' => 'Zealot', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 0, 'sup' => 2),
		0x090B01 => array('desc' => 'trains a Stalker', 'name' => 'Stalker', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 125, 'gas' => 50, 'sup' => 2),
		0x090B03 => array('desc' => 'trains a High templar', 'name' => 'High templar', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 150, 'sup' => 2),
		0x090B04 => array('desc' => 'trains a Dark templar', 'name' => 'Dark templar', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 125, 'gas' => 125, 'sup' => 2),
		0x090B05 => array('desc' => 'trains a Sentry', 'name' => 'Sentry', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 100, 'sup' => 2),
		0x090C00 => array('desc' => 'builds a Phoenix', 'name' => 'Phoenix', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 100, 'sup' => 2),
		0x090C02 => array('desc' => 'builds a Carrier', 'name' => 'Carrier', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 350, 'gas' => 250, 'sup' => 6),
		0x090C04 => array('desc' => 'builds a Void ray', 'name' => 'Void ray', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 150, 'sup' => 3),
		0x090D00 => array('desc' => 'builds a Warp prism', 'name' => 'Warp prism', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 0, 'sup' => 1),
		0x090D01 => array('desc' => 'builds an Observer', 'name' => 'Observer', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 100, 'sup' => 1),
		0x090D02 => array('desc' => 'builds a Colossus', 'name' => 'Colossus', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 200, 'sup' => 6),
		0x090D03 => array('desc' => 'builds an Immortal', 'name' => 'Immortal', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 100, 'sup' => 4),
		0x090E00 => array('desc' => 'trains a Probe', 'name' => 'Probe', 'type' => SC2_TYPEWORKER, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 0, 'sup' => 1),
		0x090F00 => array('desc' => 'uses Psionic storm (High templar)', 'name' => 'Psionic storm (High templar)', 'type' => SC2_TYPEABILITY),
		0x0A0200 => array('desc' => 'builds an Interceptor (Carrier)', 'name' => 'Interceptor (Carrier)', 'type' => SC2_TYPEABILITY, 'min' => 25),
		0x0A0300 => array('desc' => 'researches Ground weapons level 1', 'name' => 'Ground weapons L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0301 => array('desc' => 'researches Ground weapons level 2', 'name' => 'Ground weapons L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x0A0302 => array('desc' => 'researches Ground weapons level 3', 'name' => 'Ground weapons L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x0A0303 => array('desc' => 'researches Ground armor level 1', 'name' => 'Ground weapons L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0304 => array('desc' => 'researches Ground armor level 2', 'name' => 'Ground weapons L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x0A0305 => array('desc' => 'researches Ground armor level 3', 'name' => 'Ground weapons L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 225, 'gas' => 225),
		0x0A0306 => array('desc' => 'researches Shields level 1', 'name' => 'Shields L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 200),
		0x0A0307 => array('desc' => 'researches Shields level 2', 'name' => 'Shields L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 300),
		0x0A0308 => array('desc' => 'researches Shields level 3', 'name' => 'Shields L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 400, 'gas' => 400),
		0x0A0401 => array('desc' => 'researches Gravitic boosters', 'name' => 'Gravitic boosters', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0402 => array('desc' => 'researches Gravitic drive', 'name' => 'Gravitic drive', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0405 => array('desc' => 'researches Extended thermal lance', 'name' => 'Extended thermal lance', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 200),
		0x0A0500 => array('desc' => 'researches Khaydarin amulet', 'name' => 'Khaydarin amulet', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0A0504 => array('desc' => 'researches Psionic storm', 'name' => 'Psionic storm', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 200),
		0x0C0500 => array('desc' => 'warps in a Zealot (Warp gate)', 'name' => 'Zealot', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 0, 'sup' => 2),
		0x0C0501 => array('desc' => 'warps in a Stalker (Warp gate)', 'name' => 'Stalker', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 125, 'gas' => 50, 'sup' => 2),
		0x0C0503 => array('desc' => 'warps in a High templar (Warp gate)', 'name' => 'High templar', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 150, 'sup' => 2),
		0x0C0504 => array('desc' => 'warps in a Dark templar (Warp gate)', 'name' => 'Dark templar', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 125, 'gas' => 125, 'sup' => 2),
		0x0C0505 => array('desc' => 'warps in a Sentry (Warp gate)', 'name' => 'Sentry', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 100, 'sup' => 2),
		0x0C0900 => array('desc' => 'uses Blink (Stalker)', 'name' => 'Blink (Stalker)', 'type' => SC2_TYPEABILITY),
		0x0D0800 => array('desc' => 'uses Force field (Sentry)', 'name' => 'Force field (Sentry)', 'type' => SC2_TYPEABILITY),
		0x0D0900 => array('desc' => 'switches to Phasing mode (Warp prism)', 'name' => 'Phasing mode (Warp prism)', 'type' => SC2_TYPEABILITY),
		0x0D0A00 => array('desc' => 'switches to Transport mode (Warp prism)', 'name' => 'Transport mode (Warp prism)', 'type' => SC2_TYPEABILITY),
		0x0D0C00 => array('desc' => 'researches Air weapons level 1', 'name' => 'Air weapons L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0D0C01 => array('desc' => 'researches Air weapons level 2', 'name' => 'Air weapons L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x0D0C02 => array('desc' => 'researches Air weapons level 3', 'name' => 'Air weapons L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x0D0C03 => array('desc' => 'researches Air armor level 1', 'name' => 'Air armor L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0D0C04 => array('desc' => 'researches Air armor level 2', 'name' => 'Air armor L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 225, 'gas' => 225),
		0x0D0C05 => array('desc' => 'researches Air armor level 3', 'name' => 'Air armor L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 300),
		0x0D0C06 => array('desc' => 'researches Warp gate', 'name' => 'Warp gate', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 50),
		0x0D0C09 => array('desc' => 'researches Hallucination', 'name' => 'Hallucination', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0D0D00 => array('desc' => 'researches Charge', 'name' => 'Charge', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 200),
		0x0D0D01 => array('desc' => 'researches Blink', 'name' => 'Blink', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0D0400 => array('desc' => 'transforms to Warp gate (Gateway)', 'name' => 'transform to Warp gate (Gateway)', 'type' => SC2_TYPEBUILDINGUPGRADE),
		0x0D0500 => array('desc' => 'transforms to Gateway (Warp gate)', 'name' => 'transform to Gateway (Warp gate)', 'type' => SC2_TYPEBUILDINGUPGRADE),
		0x0E0200 => array('desc' => 'uses Vortex (Mothership)', 'name' => 'Vortex (Mothership)', 'type' => SC2_TYPEABILITY),
		0x0F0B00 => array('desc' => 'warps in an Archon', 'name' => 'Archon', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE),

		// zerg
		0x030000 => array('desc' => 'uses Corruption (Corruptor)', 'name' => 'Corruption (Corruptor)', 'type' => SC2_TYPEABILITY),
		0x030400 => array('desc' => 'uses Explode (Baneling)', 'name' => 'Explode (Baneling)', 'type' => SC2_TYPEABILITY),
		0x030600 => array('desc' => 'uses Fungal growth (Infestor)', 'name' => 'Fungal growth (Infestor)', 'type' => SC2_TYPEABILITY),
		0x030900 => array('desc' => 'morphs into a Baneling (Zergling)', 'name' => 'Baneling', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 25, 'gas' => 25),
		0x040F00 => array('desc' => 'uses Spawn changeling (Overseer)', 'name' => 'Changeling', 'type' => SC2_TYPEABILITY),
		0x050A01 => array('desc' => 'sets worker rally point (Hatchery)', 'name' => 'worker rally point (Hatchery)', 'type' => SC2_TYPEGEN),
		0x050A00 => array('desc' => 'sets rally point (Hatchery)', 'name' => 'rally point (Hatchery)', 'type' => SC2_TYPEGEN),
		0x050B01 => array('desc' => 'researches Glial reconstitution', 'name' => 'Glial reconstitution', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x050B02 => array('desc' => 'researches Tunneling claws', 'name' => 'Tunneling claws', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x050C00 => array('desc' => 'uses Attack building (Baneling)', 'name' => 'Attack building (Baneling)', 'type' => SC2_TYPEABILITY),
		0x050D00 => array('desc' => 'uses Spawn infested terran (Overseer)', 'name' => 'Infested terran', 'type' => SC2_TYPEABILITY),
		0x050E00 => array('desc' => 'uses Neural parasite (Infestor)', 'name' => 'Neural parasite (Infestor)', 'type' => SC2_TYPEABILITY),
		0x050F00 => array('desc' => 'uses Spawn larvae (Queen)', 'name' => 'Spawn larvae (Queen)', 'type' => SC2_TYPEABILITY),
		0x060502 => array('desc' => 'researches Chitinous plating', 'name' => 'Chitinous plating', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0A0600 => array('desc' => 'builds a Hatchery', 'name' => 'Hatchery', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 0),
		0x0A0602 => array('desc' => 'builds an Extractor', 'name' => 'Extractor', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 0),
		0x0A0603 => array('desc' => 'builds a Spawning pool', 'name' => 'Spawning pool', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 0),
		0x0A0604 => array('desc' => 'builds an Evolution chamber', 'name' => 'Evolution chamber', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 75, 'gas' => 0),
		0x0A0605 => array('desc' => 'builds a Hydralisk den', 'name' => 'Hydralisk den', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0606 => array('desc' => 'builds a Spire', 'name' => 'Spire', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 200),
		0x0A0607 => array('desc' => 'builds an Ultralisk cavern', 'name' => 'Ultralisk cavern', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 200),
		0x0A0608 => array('desc' => 'builds an Infestation pit', 'name' => 'Infestation pit', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0609 => array('desc' => 'builds a Nydus network', 'name' => 'Nydus network', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 200),
		0x0A060A => array('desc' => 'builds a Baneling nest', 'name' => 'Baneling nest', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 50),
		0x0A060D => array('desc' => 'builds a Roach warren', 'name' => 'Roach warren', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 0),
		0x0A060E => array('desc' => 'builds a Spine crawler', 'name' => 'Spine crawler', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 0),
		0x0A060F => array('desc' => 'builds a Spore crawler', 'name' => 'Spore crawler', 'type' => SC2_TYPEBUILDING, 'subtype' => SC2_SUBTYPECREATE, 'min' => 75, 'gas' => 0),
		0x0A0701 => array('desc' => 'returns cargo (Drone)', 'name' => 'return cargo (Drone)', 'type' => SC2_TYPEGEN),
		0x0A0800 => array('desc' => 'researches Melee attacks level 1', 'name' => 'Melee attacks L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0801 => array('desc' => 'researches Melee attacks level 2', 'name' => 'Melee attacks L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x0A0802 => array('desc' => 'researches Melee attacks level 3', 'name' => 'Melee attacks L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x0A0803 => array('desc' => 'researches Ground carapace level 1', 'name' => 'Ground carapace L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0A0804 => array('desc' => 'researches Ground carapace level 2', 'name' => 'Ground carapace L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 225, 'gas' => 225),
		0x0A0805 => array('desc' => 'researches Ground carapace level 3', 'name' => 'Ground carapace L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 300),
		0x0A0806 => array('desc' => 'researches Missile attacks level 1', 'name' => 'Missile attacks L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0807 => array('desc' => 'researches Missile attacks level 2', 'name' => 'Missile attacks L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x0A0808 => array('desc' => 'researches Missile attacks level 3', 'name' => 'Missile attacks L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x0A080A => array('desc' => 'researches Burrow', 'name' => 'Burrow', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0900 => array('desc' => 'mutates into Lair (Hatchery)', 'name' => 'mutate into Lair (Hatchery)', 'type' => SC2_TYPEBUILDINGUPGRADE, 'min' => 150, 'gas' => 100),
		0x0A0A00 => array('desc' => 'mutates into Hive (Lair)', 'name' => 'mutate into Hive (Lair)', 'type' => SC2_TYPEBUILDINGUPGRADE, 'min' => 200, 'gas' => 150),
		0x0A0B00 => array('desc' => 'mutates into Greater spire (Spire)', 'name' => 'mutate into Greater spire (Spire)', 'type' => SC2_TYPEBUILDINGUPGRADE, 'min' => 200, 'gas' => 150),
		0x0A0C01 => array('desc' => 'researches Pneumatized carapace', 'name' => 'Pneumatized carapace', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0C02 => array('desc' => 'researches Ventral sacs', 'name' => 'Ventral sacs', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 200),
		0x0A0D00 => array('desc' => 'researches Adrenal glands', 'name' => 'Adrenal glands', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 200, 'gas' => 200),
		0x0A0D01 => array('desc' => 'researches Metabolic boost', 'name' => 'Metabolic boost', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0E02 => array('desc' => 'researches Grooved spines', 'name' => 'Grooved spines', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0A0F00 => array('desc' => 'researches Flyer attacks level 1', 'name' => 'Flyer attacks L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100),
		0x0A0F01 => array('desc' => 'researches Flyer attacks level 2', 'name' => 'Flyer attacks L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 175, 'gas' => 175),
		0x0A0F02 => array('desc' => 'researches Flyer attacks level 3', 'name' => 'Flyer attacks L3', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 250, 'gas' => 250),
		0x0A0F03 => array('desc' => 'researches Flyer carapace level 1', 'name' => 'Flyer carapace L1', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0A0F04 => array('desc' => 'researches Flyer carapace level 2', 'name' => 'Flyer carapace L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 225, 'gas' => 225),
		0x0A0F05 => array('desc' => 'researches Flyer carapace level 2', 'name' => 'Flyer carapace L2', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 300),
		0x0B0000 => array('desc' => 'trains a Drone', 'name' => 'Drone', 'type' => SC2_TYPEWORKER, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 0, 'sup' => 1),
		0x0B0001 => array('desc' => 'trains a pair of Zerglings', 'name' => 'Zergling x 2', 'type' => SC2_TYPEWORKER, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 0, 'sup' => 1),
		0x0B0002 => array('desc' => 'trains an Overlord', 'name' => 'Overlord', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 0, 'sup' => 0),
		0x0B0003 => array('desc' => 'trains a Hydralisk', 'name' => 'Hydralisk', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 50, 'sup' => 2),
		0x0B0004 => array('desc' => 'trains a Mutalisk', 'name' => 'Mutalisk', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 100, 'sup' => 2),
		0x0B0006 => array('desc' => 'trains an Ultralisk', 'name' => 'Ultralisk', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 300, 'gas' => 200, 'sup' => 6),
		0x0B0009 => array('desc' => 'trains a Roach', 'name' => 'Roach', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 75, 'gas' => 25, 'sup' => 2),
		0x0B000A => array('desc' => 'trains an Infestor', 'name' => 'Infestor', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 100, 'gas' => 150, 'sup' => 2),
		0x0B000B => array('desc' => 'trains a Corruptor', 'name' => 'Corruptor', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 100, 'sup' => 2),
		0x0B0100 => array('desc' => 'morphs into a Brood lord (Corruptor)', 'name' => 'Brood lord', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150, 'sup' => 2),
		0x0B0200 => array('desc' => 'uses Burrow (Baneling)', 'name' => 'Burrow (Baneling)', 'type' => SC2_TYPEABILITY),
		0x0B0300 => array('desc' => 'uses Unburrow (Baneling)', 'name' => 'Unburrow (Baneling)', 'type' => SC2_TYPEABILITY),
		0x0B0400 => array('desc' => 'uses Burrow (Drone)', 'name' => 'Burrow (Drone)', 'type' => SC2_TYPEABILITY),
		0x0B0500 => array('desc' => 'uses Unburrow (Drone)', 'name' => 'Unburrow (Drone)', 'type' => SC2_TYPEABILITY),
		0x0B0600 => array('desc' => 'uses Burrow (Hydralisk)', 'name' => 'Burrow (Hydralisk)', 'type' => SC2_TYPEABILITY),
		0x0B0700 => array('desc' => 'uses Unburrow (Hydralisk)', 'name' => 'Unburrow (Hydralisk)', 'type' => SC2_TYPEABILITY),
		0x0B0800 => array('desc' => 'uses Burrow (Roach)', 'name' => 'Burrow (Roach)', 'type' => SC2_TYPEABILITY),
		0x0B0900 => array('desc' => 'uses Unburrow (Roach)', 'name' => 'Unburrow (Roach)', 'type' => SC2_TYPEABILITY),
		0x0B0A00 => array('desc' => 'uses Burrow (Zergling)', 'name' => 'Burrow (Zergling)', 'type' => SC2_TYPEABILITY),
		0x0B0B00 => array('desc' => 'uses Unburrow (Zergling)', 'name' => 'Unburrow (Zergling)', 'type' => SC2_TYPEABILITY),
		0x0C0200 => array('desc' => 'loads units (Overlord)', 'name' => 'load units (Overlord)', 'type' => SC2_TYPEGEN),
		0x0C0202 => array('desc' => 'unloads all (Overlord)', 'name' => 'unload all (Overlord)', 'type' => SC2_TYPEGEN),
		0x0C0600 => array('desc' => 'uses Burrow (Queen)', 'name' => 'Burrow (Queen)', 'type' => SC2_TYPEABILITY),
		0x0C0700 => array('desc' => 'uses Unburrow (Queen)', 'name' => 'Unburrow (Queen)', 'type' => SC2_TYPEABILITY),
		0x0C0800 => array('desc' => 'loads units (Nydus network)', 'name' => 'load units (Nydus network)', 'type' => SC2_TYPEGEN),
		0x0C0801 => array('desc' => 'unloads all (Nydus network)', 'name' => 'unload all (Nydus network)', 'type' => SC2_TYPEGEN),
		0x0C0A00 => array('desc' => 'uses Burrow (Infestor)', 'name' => 'Burrow (Infestor)', 'type' => SC2_TYPEABILITY),
		0x0C0B00 => array('desc' => 'uses Unburrow (Infestor)', 'name' => 'Unburrow (Infestor)', 'type' => SC2_TYPEABILITY),
		0x0C0C00 => array('desc' => 'morphs into an Overseer (Overlord)', 'name' => 'Overseer', 'type' => SC2_TYPEUNIT, 'subtype' => SC2_SUBTYPECREATE, 'min' => 50, 'gas' => 100),
		0x0C0F02 => array('desc' => 'researches Pathogen glands', 'name' => 'Pathogen glands', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0C0F03 => array('desc' => 'researches Neural parasite', 'name' => 'Neural parasite', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0D0000 => array('desc' => 'researches Centrifugal hooks', 'name' => 'Centrifugal hooks', 'type' => SC2_TYPEUPGRADE, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 150),
		0x0E0300 => array('desc' => 'trains a Queen', 'name' => 'Queen', 'type' => SC2_TYPEWORKER, 'subtype' => SC2_SUBTYPECREATE, 'min' => 150, 'gas' => 0, 'sup' => 2),
		0x0E0500 => array('desc' => 'uses Transfusion (Queen)', 'name' => 'uses Transfusion (Queen)', 'type' => SC2_TYPEABILITY),
		0x0F0300 => array('desc' => 'uses Generate creep (Overlord)', 'name' => 'Generate creep (Overlord)', 'type' => SC2_TYPEABILITY),
		0x0F0301 => array('desc' => 'stops using Generate creep (Overlord)', 'name' => 'stop using Generate creep (Overlord)', 'type' => SC2_TYPEABILITY),
		0x0F0400 => array('desc' => 'uses Spawn creep tumor (Queen)', 'name' => 'Spawn creep tumor (Queen)', 'type' => SC2_TYPEABILITY),
		0x0F0500 => array('desc' => 'uses Uproot (Spine crawler)', 'name' => 'Uproot (Spine crawler)', 'type' => SC2_TYPEABILITY),
		0x0F0600 => array('desc' => 'uses Uproot (Spore crawler)', 'name' => 'Uproot (Spore crawler)', 'type' => SC2_TYPEABILITY),
		0x0F0700 => array('desc' => 'uses Root (Spine crawler)', 'name' => 'Root (Spine crawler)', 'type' => SC2_TYPEABILITY),
		0x0F0800 => array('desc' => 'uses Root (Spore crawler)', 'name' => 'Root (Spore crawler)', 'type' => SC2_TYPEABILITY),
		0x0F0900 => array('desc' => 'uses Spawn creep tumor (Creep tumor)', 'name' => 'Spawn creep tumor (Creep tumor)', 'type' => SC2_TYPEABILITY),
		0x0F0C00 => array('desc' => 'summons Nydus worm (Nydus network)', 'name' => 'summon Nydus worm (Nydus network)', 'type' => SC2_TYPEABILITY, 'min' => 100, 'gas' => 100),
		0x100200 => array('desc' => 'uses Contaminate (Overseer)', 'name' => 'Contaminate (Overseer)', 'type' => SC2_TYPEABILITY),

		// generic

		0x020400 => array('desc' => 'stops', 'name' => 'stop', 'type' => SC2_TYPEGEN),
		0x020600 => array('desc' => 'moves', 'name' => 'move', 'type' => SC2_TYPEGEN),
		0x020601 => array('desc' => 'patrols', 'name' => 'patrol', 'type' => SC2_TYPEGEN),
		0x020602 => array('desc' => 'holds position', 'name' => 'hold position', 'type' => SC2_TYPEGEN),
		0x020900 => array('desc' => 'attacks', 'name' => 'attack', 'type' => SC2_TYPEGEN),
		0x060800 => array('desc' => 'gathers', 'name' => 'gather', 'type' => SC2_TYPEGEN),
		0xFFFF0F => array('desc' => 'right-clicks', 'name' => 'right-click', 'type' => SC2_TYPEGEN)
	);
}

?>